<script setup>
import { ref, computed } from 'vue';
import { Copy, Check, RefreshCw, AlertTriangle } from 'lucide-vue-next';
import Skeleton from '../Common/Skeletons/Skeleton.vue';
import BaseButton from '../Common/BaseButton.vue';
import CentralTwoFactorCodeForm from './CentralTwoFactorCodeForm.vue';

const props = defineProps({
  setup: { type: Object, default: null },
  isLoading: { type: Boolean, default: false },
  loadError: { type: String, default: '' },
  isSubmitting: { type: Boolean, default: false },
  error: { type: String, default: '' },
});

const emit = defineEmits(['confirm', 'retry']);

const copied = ref(false);

/**
 * The QR SVG is generated by our server, but it is still never injected with v-html:
 * it is rendered through <img> (an SVG loaded as an image cannot run scripts or touch the DOM).
 */
const qrSrc = computed(() => {
  const svg = props.setup?.qr_code_svg;
  if (typeof svg !== 'string' || !/^\s*(<\?xml[^>]*>\s*)?<svg[\s>]/i.test(svg)) return '';
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
});

const groupedSecret = computed(() => (props.setup?.secret || '').replace(/(.{4})/g, '$1 ').trim());

const copySecret = async () => {
  try {
    await navigator.clipboard.writeText(props.setup?.secret || '');
    copied.value = true;
    setTimeout(() => (copied.value = false), 2000);
  } catch {
    copied.value = false;
  }
};
</script>

<template>
  <div class="space-y-5">
    <div v-if="isLoading" class="space-y-4" aria-busy="true">
      <Skeleton width="w-48" height="h-48" rounded="rounded-2xl" class-name="mx-auto" />
      <Skeleton height="h-4" />
      <Skeleton width="w-3/4" height="h-4" />
      <Skeleton height="h-12" />
    </div>

    <div v-else-if="loadError || !setup" class="space-y-4 text-center" role="alert">
      <AlertTriangle class="w-10 h-10 mx-auto text-rose-500" aria-hidden="true" />
      <p class="text-sm font-bold text-slate-700 dark:text-slate-200">
        {{ loadError || $t('super.central_auth.setup_load_failed') }}
      </p>
      <BaseButton
        variant="secondary"
        :icon="RefreshCw"
        :label="$t('super.central_auth.retry')"
        full-width
        @click="emit('retry')"
      />
    </div>

    <template v-else>
      <p class="text-xs leading-relaxed text-slate-600 dark:text-slate-300">
        {{ $t('super.central_auth.setup_step_scan') }}
      </p>

      <div class="mx-auto w-52 h-52 rounded-2xl bg-white p-3 border border-slate-200 dark:border-slate-700">
        <img v-if="qrSrc" :src="qrSrc" :alt="$t('super.central_auth.qr_alt')" class="w-full h-full" />
      </div>

      <div class="space-y-2">
        <p class="text-xs font-bold text-slate-600 dark:text-slate-300">
          {{ $t('super.central_auth.setup_manual_key') }}
        </p>
        <div
          class="flex items-center gap-2 rounded-xl border border-slate-200 bg-slate-50 p-2 dark:border-slate-700 dark:bg-slate-800"
        >
          <code dir="ltr" class="flex-1 break-all ps-1 font-mono text-xs font-bold text-slate-900 dark:text-slate-100">
            {{ groupedSecret }}
          </code>
          <BaseButton
            size="icon"
            variant="ghost"
            :icon="copied ? Check : Copy"
            :aria-label="copied ? $t('super.central_auth.copied') : $t('super.central_auth.copy')"
            @click="copySecret"
          />
        </div>
      </div>

      <p class="text-xs leading-relaxed text-slate-600 dark:text-slate-300">
        {{ $t('super.central_auth.setup_step_confirm') }}
      </p>

      <CentralTwoFactorCodeForm
        :allow-recovery-code="false"
        :is-submitting="isSubmitting"
        :error="error"
        :submit-label="$t('super.central_auth.confirm_setup')"
        @submit="emit('confirm', $event.code)"
      />
    </template>
  </div>
</template>
