<?php

declare(strict_types=1);

namespace Tests\Unit;

use FilesystemIterator;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;
use RecursiveDirectoryIterator;
use RecursiveIteratorIterator;
use SplFileInfo;
use Tests\Concerns\DetectsRealPhoneNumbers;

/**
 * F1a / F1b / F1c / F1d regression guard: no real-looking Egyptian mobile number
 * may live in source, seeders, tests or the desktop shell. Only obvious dummies
 * (see DetectsRealPhoneNumbers) are allowed.
 *
 * Failures list FILE PATHS ONLY — a matched number is never echoed, so a CI log
 * cannot leak it again.
 *
 * Deliberately excluded (generated or awaiting an explicit CTO git decision):
 *  - resources/js/helpers/defaultTranslations.* (generated by lang:export)
 *  - tests/e2e/reports/** and e2e/.auth/** (tracked artefacts; untracking needs `git rm --cached`)
 *  - node_modules, vendor, public/build, *.sqlite
 */
final class NoHardcodedRealPhonesTest extends TestCase
{
    use DetectsRealPhoneNumbers;

    /** @var list<string> */
    private const SCANNED_EXTENSIONS = ['php', 'js', 'mjs', 'cjs', 'ts', 'vue', 'json'];

    private const EXCLUDED_PATH_PATTERN = '#(^|/)(node_modules|vendor|\.auth)/|(^|/)tests/e2e/reports/|defaultTranslations\.(js|json)$#';

    private static function backendPath(string $relative = ''): string
    {
        $base = dirname(__DIR__, 2);

        return $relative === '' ? $base : $base.'/'.$relative;
    }

    /**
     * @return array<string, array{0: string}>
     */
    public static function scannedRootsProvider(): array
    {
        return [
            'app' => ['app'],
            'database' => ['database'],
            'config' => ['config'],
            'routes' => ['routes'],
            'lang' => ['lang'],
            'resources/js' => ['resources/js'],
            'tests' => ['tests'],
            'e2e' => ['e2e'],
            'desktop/src' => ['../desktop/src'],
            'desktop/main.js' => ['../desktop/main.js'],
        ];
    }

    #[DataProvider('scannedRootsProvider')]
    public function test_source_tree_contains_no_real_looking_phone_numbers(string $root): void
    {
        $path = self::backendPath($root);
        $this->assertTrue(file_exists($path), "Scanned root is missing: {$root}");

        $offenders = [];

        foreach ($this->filesUnder($path) as $file) {
            $relative = $this->relativePath($file->getPathname());

            if (preg_match(self::EXCLUDED_PATH_PATTERN, $relative) === 1) {
                continue;
            }

            if (! in_array(strtolower($file->getExtension()), self::SCANNED_EXTENSIONS, true)) {
                continue;
            }

            $contents = (string) file_get_contents($file->getPathname());
            $count = self::countRealLookingPhones($contents);

            if ($count > 0) {
                $offenders[] = "{$relative} ({$count} distinct)";
            }
        }

        $this->assertSame(
            [],
            $offenders,
            "Real-looking phone numbers found under {$root}. Replace them with obvious dummies (e.g. 01000000001). Values are intentionally not printed."
        );
    }

    public function test_dummy_classifier_accepts_obvious_dummies(): void
    {
        foreach (['01000000001', '01000000010', '01000000020', '01011111111', '01222222201', '01012345678'] as $dummy) {
            $this->assertTrue(self::isObviousDummyPhone($dummy), 'Expected an obvious dummy to be accepted.');
        }
    }

    public function test_dummy_classifier_rejects_realistic_numbers(): void
    {
        // Synthetic but realistic-looking shapes; built by concatenation so this file
        // never contains a full realistic literal that the guard itself would flag.
        foreach (['010'.'93827461', '011'.'28374659', '015'.'62738495', '012'.'20394857'] as $realistic) {
            $this->assertFalse(self::isObviousDummyPhone($realistic), 'Expected a realistic-looking number to be rejected.');
        }
    }

    /**
     * @return iterable<SplFileInfo>
     */
    private function filesUnder(string $path): iterable
    {
        if (is_file($path)) {
            yield new SplFileInfo($path);

            return;
        }

        $iterator = new RecursiveIteratorIterator(
            new RecursiveDirectoryIterator($path, FilesystemIterator::SKIP_DOTS)
        );

        /** @var SplFileInfo $file */
        foreach ($iterator as $file) {
            if ($file->isFile()) {
                yield $file;
            }
        }
    }

    private function relativePath(string $absolute): string
    {
        $absolute = str_replace('\\', '/', $absolute);
        $base = str_replace('\\', '/', self::backendPath()).'/';

        return str_starts_with($absolute, $base) ? substr($absolute, strlen($base)) : $absolute;
    }
}
